[package]
authors = ["Matthias Endler <matthias.endler@trivago.com>"]
name = "lqip"
version = "0.1.0"

[dependencies]
clap = "2.26.0"
duct = "0.9.1"
error-chain = "0.11.0"
lazy_static = "0.2.8"
select = "0.4.2"
tempdir = "0.3.5"
tera = "0.10.10"
